### ISSUE TITLE
jjtree/java: invalid return type in the generated Eg4Visitor class

### ISSUE THREAD

**Issue by zosrothko** [javacc/codegenerator#39]
Hi

With examples/JJTreeExamples/eg4.jjt
javacc-8.0.0 generates
```
/* Generated By:JavaCC: Do not edit this line. Eg4Visitor.java Version 8.0.0 */
public interface Eg4Visitor
{
  public void visit(SimpleNode node, Object data);
  public void visit(ASTStart node, Object data);
  public void visit(ASTAdd node, Object data);
  public void visit(ASTMult node, Object data);
  public void visit(ASTMyOtherID node, Object data);
  public void visit(ASTInteger node, Object data);
}
/* JavaCC - OriginalChecksum=7f18c07430b30247dbdee935f9a72582 (do not edit this line) */
```
javacc-7.0.6 generates
```
/* Generated By:JavaCC: Do not edit this line. Eg4Visitor.java Version 7.0.6 */
public interface Eg4Visitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTAdd node, Object data);
  public Object visit(ASTMult node, Object data);
  public Object visit(ASTMyOtherID node, Object data);
  public Object visit(ASTInteger node, Object data);
}
/* JavaCC - OriginalChecksum=a095f8ae3c7e1a77182789d3924bb5a6 (do not edit this line) */
```

**Comment by mbrigl** [comment]
Caused by JJTreeOptions

```
if (JavaCCGlobals.getCodeGenerator() != null) { 
  Options.optionValues.put("VISITOR_RETURN_TYPE", "Object"); 
} else { 
  Options.optionValues.put("VISITOR_RETURN_TYPE", "void"); 
} 
```
where in JavaCC 7 only following line is defined.

`Options.optionValues.put("VISITOR_RETURN_TYPE", "Object"); 
`

At this point getCodeGenerator is null, because the arguments are parsed later. I don't understand the sense why the presence of a CodeGenerator should define the return type

**Comment by zosrothko** [comment]
May be to differenciate between java from c++ generation

**Comment by mbrigl** [comment]
> May be to differenciate between java from c++ generation

Than it should not work in v.7 with C++, in case a return type is defined

**Comment by mbrigl** [comment]
Checked the implementation. The option should be set to like in JavaCC 7, as in Cpp the type 'Object' will be replaced by void.
`
Options.optionValues.put("VISITOR_RETURN_TYPE", "Object");
`
A cleaner approach would be an empty string as default, but this has a bigger impact.

**Comment by mbrigl** [comment]
fixed with pull request [139 on javacc](https://github.com/javacc/javacc/pull/139)

**Comment by zosrothko** [comment]
Verified
