### ISSUE TITLE
javacc/java: useless space in TokenManager

### ISSUE THREAD

**Issue by zosrothko** [javacc/codegenerator#56]
Hi

With javacc8, the grammar snippet below
```
TOKEN :
{
  < Id: ["a"-"z","A"-"Z"] ( ["a"-"z","A"-"Z","0"-"9"] )* > { System.out.println(matchedToken.toString()); }
}
```
generates
```
static void TokenLexicalActions(Token matchedToken) {
  switch(matchedToken.kind) {
    case 5: {

      System . out . println ( matchedToken . toString ( ) ) ; 
      break;
    }
    default: break;
  }
}
```
with useless spaces between `System`, `out`, `println`.

**Comment by mbrigl** [comment]
Resolve on the Lexer on javacc. Caused by a space on adding token images to the buffer. In javacc 7, each the whole action were a single token. in javacc 8 an action can be organized in multiple tokens.

**Comment by zosrothko** [comment]
Verified
