### ISSUE TITLE
jjtree/java: generated parser is missing some datas

### ISSUE THREAD

**Issue by zosrothko** [javacc/codegenerator#57]
Hi

with the grammar `javacc-8.0\examples\java\Interpreter\src\main\jjtree\AST.jjt`

javacc 8 generates a parser with missing data declaration
```
  static final public void VarDeclaration() throws ParseException {
    trace_call("VarDeclaration");
    try {
 Token t;          
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case BOOL:{
        jj_consume_token(BOOL);
 jjtn000.type = BOOL;                      // <<< jjtn000 cannot be resolved as a variable
        break;
        }
```
[SPLParser.java.txt](https://github.com/javacc/codegenerator/files/4175552/SPLParser.java.txt)

**Comment by mbrigl** [comment]
Cannot reproduce this problem on AST. get the error on VST, but is present on javacc7 as well

**Comment by zosrothko** [comment]
Yes, it is VST..; made a typo

**Comment by zosrothko** [comment]
Verifed
