### ISSUE TITLE
javacc/c++: compile error in generated declaration of jjToken

### ISSUE THREAD

**Issue by zosrothko** [javacc/codegenerator#62]
Hi

Got this error on VS2017
```
1>c:\users\fandre\documents\git\javacc\javacc-8.0\grammars\cpp\java_1.5\target\generated-sources\cpp\javaparsertokenmanager.cc(568): error C4146: opérateur moins unaire appliqué à un type non signé, le résultat sera non signé
```
on this statement
```
static const unsigned long long jjtoToken[] = {
   -4095ULL, -1ULL, 5ULL};
```

**Comment by mbrigl** [comment]
Resolved for C++. For Java the problem is still present as no unsigned long is supported. May be in future the implementation as value array should be replaced by a bit operation.

**Comment by zosrothko** [comment]
One question: Why the `unsigned long long` is used instead of `signed long long`? May be switching to the `signed long long` would help in generating code?

BTW, your fix is not merged in the master branch for c++

**Comment by mbrigl** [comment]
Bug should be alread merged: https://github.com/mbrigl/codegenerator/commit/baf8c8b78282ae1cf2e26e1e506116a747a7eeab

You're right, should work with signed long long

**Comment by zosrothko** [comment]
Verified
