### ISSUE TITLE
java/c++: lexical error on SKIP_TOKEN rules

### ISSUE THREAD

**Issue by zosrothko** [javacc/codegenerator#72]
Hello

With the following snippet
```
SKIP:{" "|"\t"|"\n"|"\r"|"\f"}
TOKEN:
{ <#NA:~["-","\r","\n"]>
| <#EOL:("\n"|"\r"|"\r\n")>
}

SPECIAL_TOKEN:{"--":LineComment}
<LineComment>SPECIAL_TOKEN:{<(<NA>|"-"<NA>)*(<EOL>|"-"<EOL>|"-""-")?>:DEFAULT}
```
the javacc-8.0.0 generated code, be in java or c++, does not parse properly the input below
`aa -- o-i -- bb`

Ouput should be
```
aa
bb
```
while it is currently
```
aa
 o-i
bb
```

See the full grammar & test intput in `javacc-8.0\codegen\java\bugs\bug001`. Run `mvn clean install` in this directory to build & test. Result  in `idl/idl.out` and the reference in `idl/idl.ref`

Notice that javacc-7.0.7 generates a code that is working fine: to check it, run the command:
`mvn clean install -P-jcc8 -Pjcc7`
In that case, idl/idl.out is identical to idl/idl.ref

**Comment by new-javacc** [comment]
Seems to work fine now!

**Comment by zosrothko** [comment]
Unless I missed something, it does not work on my side
For this input 
`aa -- o-i -- bb`
The output is
```
aa
 o-i
bb
```
while expected is
```
aa
bb

```
```
:\Users\fandre\Documents\git\javacc\javacc-8.0\codegen\java\bugs\bug001>git show
commit 0f15c3ab623f6e974c22ecdd06623f4ab3603464 (HEAD -> master, origin/master, origin/HEAD)
Author: Sreenivas Viswanadha <sreeni@viswanadha.net>
Date:   Sat Jan 2 15:37:27 2021 -0800
```

**Comment by new-javacc** [comment]
I think the issue is with the pom.xml picking up garbage jar. We should fix the tests to be quicker. The mavnen setup for testing in each dir is too expensive. Reopen after the maven mess is figured out and the codegenerator git setup is fixed

**Comment by new-javacc** [comment]
[INFO] --- maven-invoker-plugin:3.2.1:run (integration-test-cpp-bugs) @ cpp ---
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[WARNING] Filtering of parent/child POMs is not supported without cloning the projects
[INFO] Building: bug002/pom.xml
[INFO]           bug002/pom.xml ................................... SUCCESS (23.3 s)
[INFO] -------------------------------------------------
[INFO] Build Summary:
[INFO]   Passed: 1, Failed: 0, Errors: 0, Skipped: 0
[INFO] -------------------------------------------------
[INFO] 
[INFO] --- maven-invoker-plugin:3.2.1:run (integration-test-cpp-examples) @ cpp ---
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[WARNING] Filtering of parent/child POMs is not supported without cloning the projects
[INFO] Building: CORBA-IDL/pom.xml
[INFO]           CORBA-IDL/pom.xml ................................ SUCCESS (16.9 s)
[INFO] Building: JJTreeExamples/pom.xml
 [INFO]           JJTreeExamples/pom.xml ........................... SUCCESS (48.3 s)

**Comment by new-javacc** [comment]
sreeni@sreeni-laptop:~/newjavacc$ git show
commit b6bf13666b4657415e7818d540a9181c35d9b00d (HEAD -> release, origin/release, origin/HEAD)
Author: Francis ANDRE <francis.andre.kampbell@orange.fr>
Date:   Sun Jan 3 13:26:38 2021 +0100

    Updated

diff --git a/codegen b/codegen
index 0f15c3ab..ec10933b 160000
--- a/codegen
+++ b/codegen
@@ -1 +1 @@
-Subproject commit 0f15c3ab623f6e974c22ecdd06623f4ab3603464
+Subproject commit ec10933b0649a281abcb0769b9c208bd5c943807

**Comment by new-javacc** [comment]
Really fixed it this time!
