### ISSUE TITLE
java: invalid package generation for the "default" package

### ISSUE THREAD

**Issue by zosrothko** [javacc/codegenerator#8]
Hi
examples/CORBA-IDL/IDL.jj is defining a parser in the default java package as
```
PARSER_BEGIN(IDLParser)

public class IDLParser {
```
and the parser class is generated as
```
/* IDLParser.java */
package ;
/* Generated By:JavaCC: Do not edit this line. IDLParser.java */
public class IDLParser implements IDLParserTreeConstants , IDLParserConstants 
{


public class IDLParser {

```
which is wrong because of the `package ;` statement

**Comment by zosrothko** [comment]
With
```
PARSER_BEGIN(IDLParser)
package idl;

public class IDLParser {

  public static void main(String args[]) {
```
generated code is
```
/* IDLParser.java */
package ;
/* Generated By:JavaCC: Do not edit this line. IDLParser.java */
public class IDLParser implements IDLParserTreeConstants , IDLParserConstants 
{

package idl;

public class IDLParser {

  public static void main(String args[]) {
```

**Comment by mbrigl** [comment]
Provided a patch to resolve the problem with the "default" package.
Another problem is the parsing of Java code between the PARSER_BEGIN,PARSER_END markers. 

As the core should be independent from the target language, the JavaCCParser shouldn't know anything about the target language. The block between PARSER_BEGIN, PARSER_END should contain only the parser content, not package, import and class declarations.

I suggest to introduce properly options or blocks to declare, imports, and inheritance of an parser. The package is already covered by the NAMESPACE option.
In that way we can avoid to be target language dependent in the core.

**Comment by zosrothko** [comment]
@mbrigl An additional issue on the generated class. The generated class for a `jj` grammar, not a `jjt` one contains a reference to `IDLParserTreeConstants` which is generated only when compiling a `jjt` grammar
```
PARSER_BEGIN(IDLParser)

PARSER_END(IDLParser)

/*
 * Tokens to ignore in the BNF follow.
 */

SKIP :
{
  < " " >
| < "\t" >
| < "\n" >
| < "\r" >
| < "//" (~["\n"])* "\n" >
| <"/*" (~["*"])* "*" (~["/"] (~["*"])* "*")* "/">
| < "#" ([" ","\t"])* (["0"-"9"])+
    (([" ","\t"])* "\"" (~["\""])+ "\""
           ([" ","\t"])* (["0"-"9"])* ([" ","\t"])* (["0"-"9"])*)? "\n" >
}

/* Production 1 */

void specification() :
{}
{
  ( definition() )+
}

/* Production 2 */

void definition() :
{}
{
  type_dcl() ";"
|
  const_dcl() ";"
|
  except_dcl() ";"
|
  interfacex() ";"
|
  module() ";"
}

```
generates
```
/* IDLParser.java */
package ;
/* Generated By:JavaCC: Do not edit this line. IDLParser.java */
public class IDLParser implements IDLParserTreeConstants , IDLParserConstants 
{
```

```
[java] Java Compiler Compiler Version ??.??.?? (Parser Generator)
     [java] (type "javacc" with no arguments for help)
     [java] Reading from file ../examples/CORBA-IDL/IDL.jj . . .
     [java] Parser generated successfully.
    [javac] C:\Users\fandre\Documents\git\javacc\javacc-8.0\test\java\target\antrun\build-main.xml:15: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 7 source files
    [javac] C:\Users\fandre\Documents\git\javacc\javacc-8.0\test\java\test.tmp\CORBA-IDL\IDLParser.java:3: error: cannot find symbol
    [javac] public class IDLParser implements IDLParserTreeConstants , IDLParserConstants
    [javac]                                   ^
    [javac]   symbol: class IDLParserTreeConstants
```

**Comment by zosrothko** [comment]
@mbrigl 

> I suggest to introduce properly options or blocks to declare, imports, and inheritance of an parser. The package is already covered by the NAMESPACE option.
The NAMESPACE option is only for C++ generation. As far as I know, the package declaration in the previous 5.0 up to 7.0 version, was detected by JavaCC to generate the Java code by default in the declared package. This is a major incompatibility issue that should clearly stated and documented for the 8.0 version. Hopefully, the target package where the classes are generated can be set with a command line option.

**Comment by mbrigl** [comment]
Needs to accept pull request [108](https://github.com/javacc/javacc/pull/108) on javacc/javacc

**Comment by zosrothko** [comment]
@mbrigl Unless I am mistaken, in the latest JavaCC 8.0.0 branch and codegenerator branch, this issue is not fixed. See the JavaCC grammar at \javacc-8.0\tests\examples\CORBA-IDL\IDL.jj

IDL.jj snippet
```
PARSER_BEGIN(IDLParser)

PARSER_END(IDLParser)
```
is compiled to
```
/* IDLParser.java */
/* Generated By:JavaCC: Do not edit this line. IDLParser.java */
 implements IDLParserConstants 
```

**Comment by mbrigl** [comment]
Resolved with fix pull request #16

**Comment by zosrothko** [comment]
@mbrigl Unless I am mistaking, this issue is not yet fixed after your merge.

With the following grammar
```
PARSER_BEGIN(IDLParser)
public class IDLParser {
  public static void main(String args[]) throws Exception {
  }
}
PARSER_END(IDLParser)
```
Java 8.0.0 is producing
```
/* IDLParser.java */
/* Generated By:JavaCC: Do not edit this line. IDLParser.java */
 implements IDLParserConstants 

public class IDLParser {
  public static void main(String args[]) throws Exception {
  }
}
```

**Comment by mbrigl** [comment]
I tried again. With the latest commit I get

```
/* IDLParser.java */

/* Generated By:JavaCC: Do not edit this line. IDLParser.java */
public class IDLParser  implements IDLParserConstants {
  public static void main(String args[]) {
  }
}
```

**Comment by zosrothko** [comment]
Error from my side. Missing an git submodule update --remote
